### ISSUE TITLE
How can I use this on Windows 10?

### ISSUE THREAD

**Issue by djzwerg** [poolborges/unicenta-pos#64]
Hi, your project looks very nice and interesting. How can I use this on Windows 10? I've tried installing unicenta opos v4.5 and copying your files into the installation folder but it doesn't work :-(

**Comment by poolborges** [comment]
THIS is a independent fork

Code is based on unicenta-opos, but is not follow any development of unicenta.

Current no installation is provided (CURRENT IS DEVELOPMENT ONLY)

### Pre-requisite

**install Java 17 (From oracle)**

* https://download.oracle.com/java/17/archive/jdk-17.0.4.1_windows-x64_bin.msi

**Install MySQL (Version 5.x is Supported)**

* https://dev.mysql.com/downloads/windows/installer/5.7.html

### Application installation 

**Install Kriolos-Obiz (unzip)**

- Download: https://github.com/kriolos/kriolos-obiz/releases
-- https://github.com/kriolos/kriolos-obiz/releases/download/latest/kriolos-obiz-app-0.0.1-SNAPSHOT.zip
- Unzip (e.g C:\kriolos-obiz-app-0.0.1-SNAPSHOT\kriolos_obiz\etc
- Open file (C:\kriolos-obiz-app-0.0.1-SNAPSHOT\kriolos_obiz\etc\kriolos_obiz.conf)
- Configure location of java installation directory 
-- jdkhome="PUT_HERE_DIRECTORY_PATH_OF_JAVA"

**Comment by djzwerg** [comment]
Thanks @poolborges ! I've got it starting but it seems there is nothing working (e.g. products won't be added to the cart). I'm going to wait for the first major release and wish you all the best!
