### ISSUE TITLE
running application

### ISSUE THREAD

**Issue by Alexandre-moussa** [poolborges/unicenta-pos#73]
how can i run the application from the source code using netbeans IDE 8.2

**Comment by poolborges** [comment]
Netbeans IDE 8.2 TOO OLD


* Apache NetBeans (12; 17) https://netbeans.apache.org/
* Java  (11; 17) https://adoptium.net/temurin/releases/

But if you want just to run from code, you don't need Netbeans, from Command Prompt (See readme)
