### ISSUE TITLE
Roadmap and agenda

### ISSUE THREAD

**Issue by flutter-painter** [poolborges/unicenta-pos#75]
Hi @poolborges,

Glad to see a forkable unicenta repo in github.
I am interested in this project and have a few questions, please pardon me if opening an issue is not the appropriate way to express them. I would gladly exchange over private message or on any other channel that suit you.

Unicenta juste released a version 5.0 including notably : plugin integration, no need for Java installation and MariaDB integration.
Do you intend to fetch and include these evolutions in Kriol ?
Are there any features in Kriol that are not in current Unicenta ?
Are there future features or directions that one should be aware when considering building on one or the other ?

**Comment by poolborges** [comment]
The Unicenta 5.0 Features (I don't have access to code or executable)

Kriolos POS (I'm currently working on)

* Java 17 (Can use any Free Java Distribution)
* Better Logging 
* Java Include (No need to install separated Java) already there with jpackage (Before Announcement of Unicenta)
* Improvement of code Java 9+ features (Generic, ..., Lambdas, Stream, )
* No Much external Libraries (Don´t allow quick improvement)
* Installer Open source based on JPackage (Experimental
* Plugin (YES)
** based on SPI (Service provider Interface) META-INF/services
** Plugin for: Payment, Layout, Scripting
* Database: 
** MariaDB (Tested and supported), 
** MySQL supported but I will continue to test on

This is on going evolution of 2 years of internal improvement on this 20 years old code base 

* Unicenta - Fork Openbravo POS, that was in pass Tina POS


PS: NO ROADMAP and AGENDA YET

**Comment by poolborges** [comment]
No a real Issue

**Comment by flutter-painter** [comment]
Hi Poolborges,

Thank you for your reply and this detailed answer.
I hope a roadmap and agenda will follow-up
